CREATE DATABASE bugs;
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX, ALTER, CREATE,
LOCK TABLES, CREATE TEMPORARY TABLES, DROP, REFERENCES ON bugs.*
TO bugs@localhost IDENTIFIED BY '';
FLUSH PRIVILEGES;